RealityJinak/RealityJinak/Controllers/PriceController.cs
using System;
using System.Linq;
using System.Web.Mvc;

namespace RealityJinak.Controllers
{
    public class PriceController : Controller
    {
        // GET: Price
        public ActionResult Index()
        {
            ViewBag.Message = "Ceník služeb ";
            return View();
        }
    }
}

RealityJinak/RealityJinak/Views/Shared/ItemPrice.cshtml
@model System.String

<h5>
    <span class="label label-success">@Model kč <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></span>
</h5>

RealityJinak/RealityJinak/Views/Shared/Motto.cshtml
<h4>
    <span class="label label-success">Přesvědčte se sami <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></span>
</h4>

RealityJinak/RealityJinak/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Reality jinak</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Reality jinak", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("O nás", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Služby pro prodávající", "ServicesSellers", "Home")</li>
                        <li>@Html.ActionLink("Služby pro kupující", "ServicesBuyers", "Home")</li>
                        <li>@Html.ActionLink("Ceník služeb", "Index", "Price")</li>
                    </ul>
                    @*@Html.Partial("_LoginPartial")*@
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <div class="container">
                    <div class="row">
                        <div class="col-md-5 text-left">
                            <img src="~/Content/Pictures/RealityJinakLogo_64.png" alt="Reality jinak s.r.o.">
                        </div>
                        <div class="col-md-2 centerAdressLebsoft">
                            <address>
                                <img src="~/Content/Pictures/RealityJinak_Logo2_124.png" width="16" height="16" alt="Reality jinak s.r.o." /><strong> Reality jinak s.r.o.</strong><br>
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Ing.Markéta Lopraisová <br />
                                <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="mailto:#"> m_loprais@centrum.cz</a><br>
                                <span class="glyphicon glyphicon-phone" aria-hidden="true"></span> +420 724 761 124
                            </address>
                        </div>
                        <div class="col-md-5 text-right">
                            <img src="~/Content/Pictures/LebsoftLogo_64.png" alt="Lebsoft s.r.o.">
                        </div>
                    </div>
                </div>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>